# Generated by Django 2.1.5 on 2019-03-27 18:01

import account.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_another_user', models.BooleanField(blank=True, null=True)),
                ('main_photo', models.ImageField(blank=True, default='defult-photo.png', null=True, upload_to=account.models.user_directory_path)),
                ('number_not_read_messages', models.IntegerField(default=0, null=True)),
                ('sex', models.CharField(choices=[('Не выбрано', 'Не выбрано'), ('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Не выбрано', max_length=1000, null=True)),
                ('marital_status', models.CharField(choices=[('Не выбрано', 'Не выбрано'), ('Не женат', 'Не женат'), ('Встречаюсь', 'Встречаюсь'), ('Помолвлен', 'Помолвлен'), ('Женат', 'Женат'), ('Влюблён', 'Влюблён'), ('Всё сложно', 'Всё сложно'), ('В активном поиске', 'В активном поиске')], default='Не выбрано', max_length=2000, null=True)),
                ('birth_day', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default='1', null=True)),
                ('month_birth', models.CharField(choices=[('Января', 'Января'), ('Февраля', 'Февраля'), ('Марта', 'Марта'), ('Апреля', 'Апреля'), ('Мая', 'Мая'), ('Июня', 'Июня'), ('Июля', 'Июля'), ('Августа', 'Августа'), ('Сентября', 'Сентября'), ('Октября', 'Октября'), ('Ноября', 'Ноября'), ('Декабря', 'Декабря')], default='Января', max_length=2000, null=True)),
                ('year_birth', models.IntegerField(choices=[(2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975)], default='2005', null=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verification_uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Unique Verification UUID')),
                ('unrejected_request_number', models.IntegerField(default=0, null=True)),
                ('number_friends', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
