# Generated by Django 2.1.5 on 2019-02-06 11:12

import account.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_another_user', models.BooleanField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('main_photo', models.ImageField(blank=True, default='defult-photo.png', null=True, upload_to=account.models.user_directory_path)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_photo', models.IntegerField(null=True, unique=True)),
                ('photo', models.ImageField(blank=True, default='defult-photo.png', null=True, upload_to=account.models.user_directory_path)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='account.Account')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
