# Generated by Django 2.1.5 on 2019-02-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_massage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='massage_from_user', to='account.Account')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='massage_to_user', to='account.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='massage',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='massage',
            name='to_user',
        ),
        migrations.AddField(
            model_name='massage',
            name='dialog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='massage_to_user', to='account.Dialog'),
        ),
    ]
