# Generated by Django 2.1.5 on 2019-02-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190210_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialog_from_user', to='account.Account'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialog_to_user', to='account.Account'),
        ),
    ]
