# Generated by Django 2.1.5 on 2019-02-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190210_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='dialog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='massages', to='account.Dialog'),
        ),
    ]
