# Generated by Django 2.1.5 on 2019-02-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190210_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='to_user',
        ),
        migrations.AddField(
            model_name='dialog',
            name='users',
            field=models.ManyToManyField(null=True, related_name='dialogs', to='account.Account'),
        ),
    ]
