# Generated by Django 2.1.5 on 2019-02-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190211_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='dialogs', to='account.Account'),
        ),
    ]
