# Generated by Django 2.1.5 on 2019-02-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190211_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='id_dialog',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
