# Generated by Django 2.1.5 on 2019-02-13 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_massage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='is_readed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='massage',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
