# Generated by Django 2.1.5 on 2019-02-13 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190213_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 13, 13, 50, 21, 141509, tzinfo=utc), null=True),
        ),
    ]
