# Generated by Django 2.1.5 on 2019-02-13 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190213_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
