# Generated by Django 2.1.5 on 2019-02-13 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190213_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='interlocutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs_for_interlocutor', to='account.Account'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='dialogs', to='account.Account'),
        ),
    ]
