# Generated by Django 2.1.5 on 2019-02-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20190222_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='users',
        ),
        migrations.AddField(
            model_name='dialog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='account.Account'),
        ),
    ]
