# Generated by Django 2.1.5 on 2019-02-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20190223_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='account.Post'),
        ),
    ]
