# Generated by Django 2.1.5 on 2019-02-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20190224_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='user',
        ),
        migrations.AddField(
            model_name='dialog',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='dialogs', to='account.Account'),
        ),
    ]
