# Generated by Django 2.1.5 on 2019-02-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20190224_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='count_not_readed_massges',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
