# Generated by Django 2.1.5 on 2019-02-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_account_count_not_readed_massges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='count_not_readed_massges',
            new_name='count_not_readed_massages',
        ),
    ]
