# Generated by Django 2.1.5 on 2019-03-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20190301_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='count_subscribers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
