# Generated by Django 2.1.5 on 2019-03-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_group_count_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fixed_post',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
