# Generated by Django 2.1.5 on 2019-03-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20190309_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='like_put',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='like_put',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
