# Generated by Django 2.1.5 on 2019-03-10 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20190310_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='account.Dialog')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=150, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('is_readed', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupmassages',
            name='dialog',
        ),
        migrations.RemoveField(
            model_name='massage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='massage',
            name='group_massages',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='count_not_readed_massages',
            new_name='count_not_readed_messages',
        ),
        migrations.DeleteModel(
            name='GroupMassages',
        ),
        migrations.DeleteModel(
            name='Massage',
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='account.Account'),
        ),
        migrations.AddField(
            model_name='message',
            name='group_messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='account.GroupMessages'),
        ),
    ]
