# Generated by Django 2.1.5 on 2019-03-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_auto_20190310_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessages',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='account.Account'),
        ),
    ]
