# Generated by Django 2.1.5 on 2019-03-10 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_message_dialog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
