# Generated by Django 2.1.5 on 2019-03-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_dialog_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_readed',
            new_name='is_read',
        ),
    ]
