# Generated by Django 2.1.5 on 2019-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_auto_20190311_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='number_not_read_messages',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
