# Generated by Django 2.1.5 on 2019-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_dialog_number_not_read_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='count_not_readed_messages',
            new_name='number_not_read_messages',
        ),
        migrations.AlterField(
            model_name='dialog',
            name='id_dialog',
            field=models.IntegerField(null=True),
        ),
    ]
