# Generated by Django 2.1.5 on 2019-03-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_auto_20190311_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='store',
        ),
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=7, null=True),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
