# Generated by Django 2.1.5 on 2019-03-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_auto_20190314_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.CharField(choices=[('Не выбранно', 'Не выбранно'), ('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Не выбранно', max_length=7, null=True),
        ),
    ]
