# Generated by Django 2.1.5 on 2019-03-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20190314_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.CharField(choices=[('Не выбрано', 'Не выбрано'), ('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Не выбрано', max_length=7, null=True),
        ),
    ]
