# Generated by Django 2.1.5 on 2019-03-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_auto_20190314_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='marital_status',
            field=models.CharField(choices=[('Не выбрано', 'Не выбрано'), ('Не женат', 'Не женат'), ('Встречаюсь', 'Встречаюсь'), ('Помолвлен', 'Помолвлен'), ('Женат', 'Женат'), ('Влюблён', 'Влюблён'), ('Всё сложно', 'Всё сложно'), ('В активном поиске', 'В активном поиске')], default='Не выбрано', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.CharField(choices=[('Не выбрано', 'Не выбрано'), ('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Не выбрано', max_length=10, null=True),
        ),
    ]
