# Generated by Django 2.1.5 on 2019-03-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_auto_20190314_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_of_birth',
        ),
    ]
