# Generated by Django 2.1.5 on 2019-03-14 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_remove_account_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fixed_post',
        ),
        migrations.AddField(
            model_name='group',
            name='fixed_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_group', to='account.Post'),
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='group', to='account.Account'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='images', to='account.Post'),
        ),
    ]
