# Generated by Django 2.1.5 on 2019-03-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_auto_20190315_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='user',
            new_name='subscribers',
        ),
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='group_for_admin', to='account.Account'),
        ),
    ]
