# Generated by Django 2.1.5 on 2019-03-16 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_auto_20190315_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
