# Generated by Django 2.1.5 on 2019-03-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_auto_20190316_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='account',
            name='verification_uuid',
        ),
    ]
