# Generated by Django 2.1.5 on 2019-02-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, db_index=True)),
                ('img', models.ImageField(blank=True, max_length=10000, upload_to='')),
            ],
        ),
    ]
