# Generated by Django 2.1.5 on 2019-03-27 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('content', models.CharField(max_length=1500, null=True)),
                ('like_put', models.BooleanField(default=False, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='account.Account')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='group.Group')),
                ('who_liked', models.ManyToManyField(blank=True, related_name='post', to='account.Account')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
