# Generated by Django 2.1.5 on 2019-03-19 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0057_auto_20190319_1507'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(max_length=150, null=True)),
                ('description', models.CharField(max_length=450, null=True)),
                ('web_site', models.CharField(max_length=150, null=True)),
                ('main_photo', models.ImageField(blank=True, default='defult-photo.png', null=True, upload_to='')),
                ('header_photo', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('count_subscribers', models.IntegerField(default=0, null=True)),
                ('admin', models.ManyToManyField(blank=True, related_name='group_for_admin', to='account.Account')),
                ('fixed_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_group', to='post.Post')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='group', to='account.Account')),
            ],
        ),
    ]
