# Generated by Django 2.1.5 on 2019-03-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='count_subscribers',
            new_name='number_subscribers',
        ),
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.ManyToManyField(related_name='group_for_admin', to='account.Account'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='web_site',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
