# Generated by Django 2.1.5 on 2019-03-27 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dialog', models.IntegerField(null=True, unique=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('number_not_read_messages', models.IntegerField(null=True)),
                ('interlocutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs_for_interlocutor', to='account.Account')),
                ('users', models.ManyToManyField(blank=True, related_name='dialogs', to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('dialog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='message.Dialog')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=150, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='account.Account')),
                ('dialog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message.Dialog')),
                ('group_messages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message.GroupMessages')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
