# Generated by Django 2.1.5 on 2019-03-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['pub_date']},
        ),
    ]
